########################################################################################################
kind: pipeline
type: docker
name: erlang-x86_64

platform:
  os: linux
  arch: amd64

clone:
  depth: 1

steps:
- name: build
  image: docker.io/alpine:3.22
  environment:
    MUSL_HASH: 71c35316aff45bbfd243d8eb9bfc4a58b6eb97cee09514cd2030e145b68107fb
    BUNNY_PASSWORD:
      from_secret: bunny_password
  commands:
    - apk update
    - apk add bash
    - bash ./compile_linux_amd64.sh $OTP_VERSION $OPENSSL_VERSION $BUNNY_PASSWORD

trigger:
  event:
    exclude:
      - cron
      - push
      - pull_request
      - tag
      - promote
      - rollback
---
########################################################################################################
kind: pipeline
type: docker
name: erlang-arm64

platform:
  os: linux
  arch: arm64

clone:
  depth: 1

steps:
- name: build
  image: docker.io/alpine:3.22
  environment:
    MUSL_HASH: 6b558025200a5ed1308e2ce2675217afec71b6c5a9d561e52262ca948d59905e
    BUNNY_PASSWORD:
      from_secret: bunny_password
  commands:
   - apk update
   - apk add bash
   - bash ./compile_linux_arm64.sh $OTP_VERSION $OPENSSL_VERSION $BUNNY_PASSWORD

trigger:
  event:
    exclude:
      - cron
      - push
      - pull_request
      - tag
      - promote
      - rollback
---
########################################################################################################
kind: pipeline
type: exec
name: erlang-macos

platform:
  os: darwin
  arch: arm64

clone:
  depth: 1

steps:
- name: build
  environment:
    BUNNY_PASSWORD:
      from_secret: bunny_password
  commands:
    - bash ./compile_macos.sh $OTP_VERSION $OPENSSL_VERSION $BUNNY_PASSWORD

trigger:
  event:
    exclude:
      - cron
      - push
      - pull_request
      - tag
      - promote
      - rollback